name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches:
      - main

jobs:
  Code-Quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Aftman installation
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 'v0.2.7'

      - name: Format
        shell: bash
        run: stylua src --check

      - name: Lint
        shell: bash
        run: selene src
